-- ============================================
-- Seed Additional Grocery Items for Mock Amazon Catalog
-- ============================================
-- This file adds 200+ common grocery items to the amazon_catalog table
-- Run this after migration-auto-ordering.sql
-- Purpose: Expand the mock "Amazon API" for better price lookups

-- Usage: psql -d grapefruit -f seed-grocery-catalog.sql

INSERT INTO amazon_catalog (id, item_name, category, price, unit, brand, in_stock) VALUES

-- Common Generic Items (for better fuzzy matching)
(gen_random_uuid(), 'Milk', 'dairy', 5.99, 'gallon', 'Great Value', true),
(gen_random_uuid(), 'Cream', 'dairy', 5.49, 'pint', 'Horizon', true),
(gen_random_uuid(), 'Cheese', 'dairy', 6.99, 'lb', 'Tillamook', true),
(gen_random_uuid(), 'Chocolate', 'pantry', 3.99, 'bar', 'Hershey''s', true),

-- DAIRY - Expanded with multiple brands and sizes
(gen_random_uuid(), 'Whole Milk', 'dairy', 4.99, 'gallon', 'Organic Valley', true),
(gen_random_uuid(), 'Whole Milk', 'dairy', 3.99, 'gallon', 'Great Value', true),
(gen_random_uuid(), '2% Milk', 'dairy', 4.49, 'gallon', 'Horizon Organic', true),
(gen_random_uuid(), '2% Milk', 'dairy', 3.79, 'gallon', 'Kroger', true),
(gen_random_uuid(), 'Skim Milk', 'dairy', 4.29, 'gallon', 'Great Value', true),
(gen_random_uuid(), 'Skim Milk', 'dairy', 4.99, 'gallon', 'Organic Valley', true),
(gen_random_uuid(), 'Half and Half', 'dairy', 3.99, 'pint', 'Land O Lakes', true),
(gen_random_uuid(), 'Heavy Cream', 'dairy', 4.99, 'pint', 'Organic Valley', true),
(gen_random_uuid(), 'Sour Cream', 'dairy', 2.99, 'container', 'Daisy', true),
(gen_random_uuid(), 'Cottage Cheese', 'dairy', 3.49, 'container', 'Good Culture', true),
(gen_random_uuid(), 'Greek Yogurt', 'dairy', 5.99, 'pack', 'Chobani', true),
(gen_random_uuid(), 'Greek Yogurt', 'dairy', 4.99, 'pack', 'Fage', true),
(gen_random_uuid(), 'Regular Yogurt', 'dairy', 3.99, 'pack', 'Yoplait', true),
(gen_random_uuid(), 'Butter', 'dairy', 4.99, 'lb', 'Land O Lakes', true),
(gen_random_uuid(), 'Butter', 'dairy', 5.99, 'lb', 'Kerrygold', true),
(gen_random_uuid(), 'Butter', 'dairy', 3.99, 'lb', 'Great Value', true),
(gen_random_uuid(), 'Cream Cheese', 'dairy', 2.99, 'package', 'Philadelphia', true),
(gen_random_uuid(), 'Whipped Cream', 'dairy', 3.49, 'can', 'Reddi-wip', true),

-- Meat & Seafood - Multiple cuts and brands
(gen_random_uuid(), 'Chicken Breast', 'meat', 7.99, 'lb', 'Tyson', true),
(gen_random_uuid(), 'Chicken Breast', 'meat', 9.99, 'lb', 'Organic Free Range', true),
(gen_random_uuid(), 'Chicken Thighs', 'meat', 5.99, 'lb', 'Tyson', true),
(gen_random_uuid(), 'Chicken Wings', 'meat', 6.99, 'lb', 'Perdue', true),
(gen_random_uuid(), 'Whole Chicken', 'meat', 4.99, 'lb', 'Perdue', true),
(gen_random_uuid(), 'Ground Beef', 'meat', 5.99, 'lb', '80/20', true),
(gen_random_uuid(), 'Ground Beef', 'meat', 7.99, 'lb', '90/10 Lean', true),
(gen_random_uuid(), 'Ground Beef', 'meat', 9.99, 'lb', 'Grass Fed Organic', true),
(gen_random_uuid(), 'Beef Steak', 'meat', 14.99, 'lb', 'Ribeye', true),
(gen_random_uuid(), 'Beef Steak', 'meat', 12.99, 'lb', 'Sirloin', true),
(gen_random_uuid(), 'Beef Steak', 'meat', 16.99, 'lb', 'Filet Mignon', true),
(gen_random_uuid(), 'Pork Chops', 'meat', 6.99, 'lb', 'Smithfield', true),
(gen_random_uuid(), 'Pork Loin', 'meat', 5.99, 'lb', 'Smithfield', true),
(gen_random_uuid(), 'Ground Pork', 'meat', 4.99, 'lb', 'Farmland', true),
(gen_random_uuid(), 'Bacon', 'meat', 8.99, 'pack', 'Wright Brand', true),
(gen_random_uuid(), 'Bacon', 'meat', 6.99, 'pack', 'Oscar Mayer', true),
(gen_random_uuid(), 'Bacon', 'meat', 11.99, 'pack', 'Nueske''s Applewood', true),
(gen_random_uuid(), 'Sausage Links', 'meat', 5.99, 'pack', 'Jimmy Dean', true),
(gen_random_uuid(), 'Italian Sausage', 'meat', 6.99, 'pack', 'Johnsonville', true),
(gen_random_uuid(), 'Hot Dogs', 'meat', 4.99, 'pack', 'Hebrew National', true),
(gen_random_uuid(), 'Turkey Breast', 'meat', 9.99, 'lb', 'Jennie-O', true),
(gen_random_uuid(), 'Ground Turkey', 'meat', 5.99, 'lb', 'Jennie-O', true),
(gen_random_uuid(), 'Salmon Fillet', 'seafood', 12.99, 'lb', 'Atlantic', true),
(gen_random_uuid(), 'Salmon Fillet', 'seafood', 16.99, 'lb', 'Wild Alaskan', true),
(gen_random_uuid(), 'Shrimp', 'seafood', 14.99, 'lb', 'Wild Caught', true),
(gen_random_uuid(), 'Shrimp', 'seafood', 12.99, 'lb', 'Farm Raised', true),
(gen_random_uuid(), 'Tilapia', 'seafood', 8.99, 'lb', 'Fresh', true),
(gen_random_uuid(), 'Cod', 'seafood', 11.99, 'lb', 'Wild Caught', true),
(gen_random_uuid(), 'Tuna Steak', 'seafood', 15.99, 'lb', 'Ahi', true),
(gen_random_uuid(), 'Crab Legs', 'seafood', 24.99, 'lb', 'Alaskan King', true),

-- Deli & Cheese - More varieties
(gen_random_uuid(), 'Sliced Turkey', 'deli', 7.99, 'lb', 'Boar''s Head', true),
(gen_random_uuid(), 'Sliced Turkey', 'deli', 5.99, 'lb', 'Hillshire Farm', true),
(gen_random_uuid(), 'Sliced Ham', 'deli', 6.99, 'lb', 'Boar''s Head', true),
(gen_random_uuid(), 'Sliced Ham', 'deli', 4.99, 'lb', 'Oscar Mayer', true),
(gen_random_uuid(), 'Salami', 'deli', 8.99, 'lb', 'Genoa', true),
(gen_random_uuid(), 'Roast Beef', 'deli', 9.99, 'lb', 'Boar''s Head', true),
(gen_random_uuid(), 'Mozzarella Cheese', 'dairy', 5.99, 'lb', 'Galbani', true),
(gen_random_uuid(), 'Cheddar Cheese', 'dairy', 6.99, 'lb', 'Tillamook', true),
(gen_random_uuid(), 'Cheddar Cheese', 'dairy', 5.49, 'lb', 'Kraft', true),
(gen_random_uuid(), 'Swiss Cheese', 'dairy', 7.99, 'lb', 'Boar''s Head', true),
(gen_random_uuid(), 'Provolone Cheese', 'dairy', 6.49, 'lb', 'Sargento', true),
(gen_random_uuid(), 'Pepper Jack Cheese', 'dairy', 6.99, 'lb', 'Tillamook', true),
(gen_random_uuid(), 'Parmesan Cheese', 'dairy', 9.99, 'block', 'BelGioioso', true),
(gen_random_uuid(), 'Feta Cheese', 'dairy', 6.99, 'container', 'Athenos', true),
(gen_random_uuid(), 'Blue Cheese', 'dairy', 8.99, 'container', 'Roquefort', true),
(gen_random_uuid(), 'Goat Cheese', 'dairy', 7.99, 'log', 'Chevre', true),
(gen_random_uuid(), 'Brie Cheese', 'dairy', 9.99, 'wheel', 'President', true),

-- PRODUCE - Extensive variety
(gen_random_uuid(), 'Apples', 'produce', 1.99, 'lb', 'Gala', true),
(gen_random_uuid(), 'Apples', 'produce', 2.49, 'lb', 'Honeycrisp', true),
(gen_random_uuid(), 'Apples', 'produce', 1.79, 'lb', 'Granny Smith', true),
(gen_random_uuid(), 'Apples', 'produce', 2.29, 'lb', 'Fuji', true),
(gen_random_uuid(), 'Bananas', 'produce', 0.59, 'lb', 'Fresh', true),
(gen_random_uuid(), 'Bananas', 'produce', 0.79, 'lb', 'Organic', true),
(gen_random_uuid(), 'Oranges', 'produce', 1.49, 'lb', 'Navel', true),
(gen_random_uuid(), 'Oranges', 'produce', 1.99, 'lb', 'Blood Orange', true),
(gen_random_uuid(), 'Strawberries', 'produce', 3.99, 'container', 'Fresh', true),
(gen_random_uuid(), 'Strawberries', 'produce', 5.99, 'container', 'Organic', true),
(gen_random_uuid(), 'Blueberries', 'produce', 4.99, 'container', 'Fresh', true),
(gen_random_uuid(), 'Raspberries', 'produce', 5.99, 'container', 'Fresh', true),
(gen_random_uuid(), 'Blackberries', 'produce', 5.49, 'container', 'Fresh', true),
(gen_random_uuid(), 'Bell Peppers', 'produce', 1.99, 'lb', 'Fresh', true),
(gen_random_uuid(), 'Bell Peppers', 'produce', 2.99, 'lb', 'Organic', true),
(gen_random_uuid(), 'Tomatoes', 'produce', 2.49, 'lb', 'Roma', true),
(gen_random_uuid(), 'Tomatoes', 'produce', 3.99, 'lb', 'Heirloom', true),
(gen_random_uuid(), 'Cherry Tomatoes', 'produce', 2.99, 'container', 'Fresh', true),
(gen_random_uuid(), 'Cucumbers', 'produce', 1.49, 'each', 'Fresh', true),
(gen_random_uuid(), 'Cucumbers', 'produce', 1.99, 'each', 'English', true),
(gen_random_uuid(), 'Lettuce', 'produce', 2.49, 'head', 'Iceberg', true),
(gen_random_uuid(), 'Lettuce', 'produce', 2.99, 'head', 'Romaine', true),
(gen_random_uuid(), 'Spinach', 'produce', 3.99, 'bag', 'Baby Spinach', true),
(gen_random_uuid(), 'Spinach', 'produce', 4.99, 'bag', 'Organic', true),
(gen_random_uuid(), 'Kale', 'produce', 2.99, 'bunch', 'Fresh', true),
(gen_random_uuid(), 'Arugula', 'produce', 3.99, 'container', 'Fresh', true),
(gen_random_uuid(), 'Broccoli', 'produce', 2.49, 'head', 'Fresh', true),
(gen_random_uuid(), 'Cauliflower', 'produce', 3.99, 'head', 'Fresh', true),
(gen_random_uuid(), 'Carrots', 'produce', 1.99, 'bag', 'Fresh', true),
(gen_random_uuid(), 'Carrots', 'produce', 2.49, 'bag', 'Organic', true),
(gen_random_uuid(), 'Celery', 'produce', 2.49, 'bunch', 'Fresh', true),
(gen_random_uuid(), 'Onions', 'produce', 1.49, 'lb', 'Yellow', true),
(gen_random_uuid(), 'Onions', 'produce', 1.79, 'lb', 'Red', true),
(gen_random_uuid(), 'Onions', 'produce', 1.99, 'lb', 'Sweet Vidalia', true),
(gen_random_uuid(), 'Green Onions', 'produce', 1.29, 'bunch', 'Fresh', true),
(gen_random_uuid(), 'Garlic', 'produce', 0.99, 'head', 'Fresh', true),
(gen_random_uuid(), 'Ginger', 'produce', 2.99, 'lb', 'Fresh', true),
(gen_random_uuid(), 'Potatoes', 'produce', 0.99, 'lb', 'Russet', true),
(gen_random_uuid(), 'Potatoes', 'produce', 1.99, 'lb', 'Yukon Gold', true),
(gen_random_uuid(), 'Potatoes', 'produce', 2.49, 'lb', 'Fingerling', true),
(gen_random_uuid(), 'Sweet Potatoes', 'produce', 1.99, 'lb', 'Fresh', true),
(gen_random_uuid(), 'Mushrooms', 'produce', 3.99, 'lb', 'Baby Bella', true),
(gen_random_uuid(), 'Mushrooms', 'produce', 4.99, 'lb', 'Shiitake', true),
(gen_random_uuid(), 'Mushrooms', 'produce', 2.99, 'lb', 'White Button', true),
(gen_random_uuid(), 'Zucchini', 'produce', 1.99, 'lb', 'Fresh', true),
(gen_random_uuid(), 'Eggplant', 'produce', 2.99, 'each', 'Fresh', true),
(gen_random_uuid(), 'Asparagus', 'produce', 4.99, 'bunch', 'Fresh', true),
(gen_random_uuid(), 'Green Beans', 'produce', 3.49, 'lb', 'Fresh', true),
(gen_random_uuid(), 'Avocado', 'produce', 1.99, 'each', 'Hass', true),
(gen_random_uuid(), 'Avocado', 'produce', 2.49, 'each', 'Organic Hass', true),
(gen_random_uuid(), 'Grapes', 'produce', 3.99, 'lb', 'Red Seedless', true),
(gen_random_uuid(), 'Grapes', 'produce', 3.99, 'lb', 'Green Seedless', true),
(gen_random_uuid(), 'Pears', 'produce', 2.49, 'lb', 'Bartlett', true),
(gen_random_uuid(), 'Pears', 'produce', 2.99, 'lb', 'Bosc', true),
(gen_random_uuid(), 'Peaches', 'produce', 2.99, 'lb', 'Fresh', true),
(gen_random_uuid(), 'Plums', 'produce', 2.49, 'lb', 'Fresh', true),
(gen_random_uuid(), 'Nectarines', 'produce', 2.99, 'lb', 'Fresh', true),
(gen_random_uuid(), 'Mango', 'produce', 1.99, 'each', 'Fresh', true),
(gen_random_uuid(), 'Pineapple', 'produce', 4.99, 'each', 'Fresh', true),
(gen_random_uuid(), 'Watermelon', 'produce', 5.99, 'each', 'Fresh', true),
(gen_random_uuid(), 'Cantaloupe', 'produce', 3.99, 'each', 'Fresh', true),
(gen_random_uuid(), 'Honeydew', 'produce', 4.49, 'each', 'Fresh', true),
(gen_random_uuid(), 'Lemons', 'produce', 0.79, 'each', 'Fresh', true),
(gen_random_uuid(), 'Limes', 'produce', 0.69, 'each', 'Fresh', true),
(gen_random_uuid(), 'Cilantro', 'produce', 1.49, 'bunch', 'Fresh', true),
(gen_random_uuid(), 'Parsley', 'produce', 1.49, 'bunch', 'Fresh', true),
(gen_random_uuid(), 'Basil', 'produce', 2.99, 'bunch', 'Fresh', true),
(gen_random_uuid(), 'Mint', 'produce', 2.49, 'bunch', 'Fresh', true),
(gen_random_uuid(), 'Dill', 'produce', 2.49, 'bunch', 'Fresh', true),
(gen_random_uuid(), 'Rosemary', 'produce', 2.99, 'bunch', 'Fresh', true),
(gen_random_uuid(), 'Thyme', 'produce', 2.99, 'bunch', 'Fresh', true),

-- Bakery - Multiple brands and types
(gen_random_uuid(), 'White Bread', 'bread', 2.99, 'loaf', 'Wonder', true),
(gen_random_uuid(), 'Wheat Bread', 'bread', 3.49, 'loaf', 'Nature''s Own', true),
(gen_random_uuid(), 'Whole Grain Bread', 'bread', 4.99, 'loaf', 'Dave''s Killer', true),
(gen_random_uuid(), 'Sourdough Bread', 'bread', 4.49, 'loaf', 'Boudin', true),
(gen_random_uuid(), 'Rye Bread', 'bread', 3.99, 'loaf', 'Pepperidge Farm', true),
(gen_random_uuid(), 'Bagels', 'bakery', 4.99, 'pack', 'Thomas', true),
(gen_random_uuid(), 'Bagels', 'bakery', 5.99, 'pack', 'Lender''s', true),
(gen_random_uuid(), 'English Muffins', 'bakery', 3.99, 'pack', 'Thomas', true),
(gen_random_uuid(), 'English Muffins', 'bakery', 4.49, 'pack', 'Bays', true),
(gen_random_uuid(), 'Tortillas', 'bakery', 3.49, 'pack', 'Mission', true),
(gen_random_uuid(), 'Flour Tortillas', 'bakery', 2.99, 'pack', 'Guerrero', true),
(gen_random_uuid(), 'Corn Tortillas', 'bakery', 2.79, 'pack', 'Mission', true),
(gen_random_uuid(), 'Pita Bread', 'bakery', 3.99, 'pack', 'Toufayan', true),
(gen_random_uuid(), 'Naan Bread', 'bakery', 4.49, 'pack', 'Stonefire', true),
(gen_random_uuid(), 'Croissants', 'bakery', 5.99, 'pack', '4-count', true),
(gen_random_uuid(), 'Dinner Rolls', 'bakery', 3.99, 'pack', 'King''s Hawaiian', true),
(gen_random_uuid(), 'Hot Dog Buns', 'bakery', 2.99, 'pack', 'Wonder', true),
(gen_random_uuid(), 'Hamburger Buns', 'bakery', 2.99, 'pack', 'Wonder', true),
(gen_random_uuid(), 'Brioche Buns', 'bakery', 4.99, 'pack', 'St Pierre', true),

-- Pantry Staples - Expanded
(gen_random_uuid(), 'All-Purpose Flour', 'pantry', 3.99, '5lb bag', 'King Arthur', true),
(gen_random_uuid(), 'All-Purpose Flour', 'pantry', 2.99, '5lb bag', 'Gold Medal', true),
(gen_random_uuid(), 'Bread Flour', 'pantry', 4.99, '5lb bag', 'King Arthur', true),
(gen_random_uuid(), 'White Sugar', 'pantry', 3.49, '4lb bag', 'Domino', true),
(gen_random_uuid(), 'Brown Sugar', 'pantry', 3.99, '2lb bag', 'Domino', true),
(gen_random_uuid(), 'Powdered Sugar', 'pantry', 2.99, 'box', 'C&H', true),
(gen_random_uuid(), 'Honey', 'pantry', 7.99, 'jar', 'Local Hive', true),
(gen_random_uuid(), 'Maple Syrup', 'pantry', 12.99, 'bottle', 'Pure Vermont', true),
(gen_random_uuid(), 'Olive Oil', 'pantry', 14.99, 'bottle', 'Extra Virgin', true),
(gen_random_uuid(), 'Vegetable Oil', 'pantry', 6.99, 'bottle', 'Wesson', true),
(gen_random_uuid(), 'Canola Oil', 'pantry', 5.99, 'bottle', 'Crisco', true),
(gen_random_uuid(), 'Coconut Oil', 'pantry', 9.99, 'jar', 'Viva Naturals', true),
(gen_random_uuid(), 'Balsamic Vinegar', 'pantry', 8.99, 'bottle', 'Modena', true),
(gen_random_uuid(), 'White Wine Vinegar', 'pantry', 2.99, 'bottle', 'Aspall', true),
(gen_random_uuid(), 'Apple Cider Vinegar', 'pantry', 4.99, 'bottle', 'Bragg', true),
(gen_random_uuid(), 'Rice Vinegar', 'pantry', 3.99, 'bottle', 'Marukan', true),

-- Rice & Grains
(gen_random_uuid(), 'White Rice', 'pantry', 4.99, '5lb bag', 'Jasmine', true),
(gen_random_uuid(), 'Brown Rice', 'pantry', 5.99, '5lb bag', 'Whole Grain', true),
(gen_random_uuid(), 'Basmati Rice', 'pantry', 8.99, '5lb bag', 'Royal', true),
(gen_random_uuid(), 'Arborio Rice', 'pantry', 6.99, 'bag', 'Risotto', true),
(gen_random_uuid(), 'Quinoa', 'pantry', 7.99, 'bag', 'Ancient Harvest', true),
(gen_random_uuid(), 'Couscous', 'pantry', 4.99, 'box', 'Near East', true),
(gen_random_uuid(), 'Oatmeal', 'pantry', 4.99, 'container', 'Quaker Oats', true),
(gen_random_uuid(), 'Steel Cut Oats', 'pantry', 6.99, 'container', 'Bob''s Red Mill', true),
(gen_random_uuid(), 'Instant Oatmeal', 'pantry', 5.99, 'box', 'Quaker', true),

-- Pasta - Multiple shapes and brands
(gen_random_uuid(), 'Spaghetti', 'pantry', 1.99, 'box', 'Barilla', true),
(gen_random_uuid(), 'Spaghetti', 'pantry', 2.49, 'box', 'De Cecco', true),
(gen_random_uuid(), 'Penne', 'pantry', 1.99, 'box', 'Barilla', true),
(gen_random_uuid(), 'Linguine', 'pantry', 1.99, 'box', 'Barilla', true),
(gen_random_uuid(), 'Fettuccine', 'pantry', 1.99, 'box', 'Barilla', true),
(gen_random_uuid(), 'Rigatoni', 'pantry', 1.99, 'box', 'Barilla', true),
(gen_random_uuid(), 'Lasagna Noodles', 'pantry', 2.99, 'box', 'Barilla', true),
(gen_random_uuid(), 'Macaroni', 'pantry', 1.49, 'box', 'Kraft', true),
(gen_random_uuid(), 'Egg Noodles', 'pantry', 2.49, 'bag', 'No Yolks', true),

-- Snacks & Chips - Many varieties
(gen_random_uuid(), 'Potato Chips', 'snacks', 3.99, 'bag', 'Lay''s Classic', true),
(gen_random_uuid(), 'Potato Chips', 'snacks', 3.99, 'bag', 'Lay''s Sour Cream', true),
(gen_random_uuid(), 'Potato Chips', 'snacks', 3.99, 'bag', 'Lay''s BBQ', true),
(gen_random_uuid(), 'Kettle Chips', 'snacks', 4.49, 'bag', 'Kettle Brand', true),
(gen_random_uuid(), 'Tortilla Chips', 'snacks', 3.49, 'bag', 'Tostitos', true),
(gen_random_uuid(), 'Tortilla Chips', 'snacks', 4.99, 'bag', 'Late July Organic', true),
(gen_random_uuid(), 'Doritos', 'snacks', 3.99, 'bag', 'Nacho Cheese', true),
(gen_random_uuid(), 'Doritos', 'snacks', 3.99, 'bag', 'Cool Ranch', true),
(gen_random_uuid(), 'Cheetos', 'snacks', 3.79, 'bag', 'Crunchy', true),
(gen_random_uuid(), 'Pretzels', 'snacks', 3.99, 'bag', 'Rold Gold', true),
(gen_random_uuid(), 'Pretzels', 'snacks', 4.49, 'bag', 'Snyder''s', true),
(gen_random_uuid(), 'Popcorn', 'snacks', 4.99, 'box', 'Orville Microwave', true),
(gen_random_uuid(), 'Popcorn Kernels', 'snacks', 3.99, 'bag', 'Orville Original', true),
(gen_random_uuid(), 'Crackers', 'snacks', 3.49, 'box', 'Ritz', true),
(gen_random_uuid(), 'Crackers', 'snacks', 4.99, 'box', 'Wheat Thins', true),
(gen_random_uuid(), 'Goldfish Crackers', 'snacks', 3.99, 'box', 'Pepperidge Farm', true),
(gen_random_uuid(), 'Cookies', 'snacks', 4.49, 'pack', 'Oreo', true),
(gen_random_uuid(), 'Cookies', 'snacks', 4.99, 'pack', 'Chips Ahoy', true),
(gen_random_uuid(), 'Cookies', 'snacks', 5.49, 'pack', 'Milano', true),
(gen_random_uuid(), 'Graham Crackers', 'snacks', 3.99, 'box', 'Honey Maid', true),
(gen_random_uuid(), 'Animal Crackers', 'snacks', 3.49, 'box', 'Barnum''s', true),
(gen_random_uuid(), 'Granola Bars', 'snacks', 5.99, 'box', 'Nature Valley', true),
(gen_random_uuid(), 'Granola Bars', 'snacks', 5.49, 'box', 'Quaker Chewy', true),
(gen_random_uuid(), 'Protein Bars', 'snacks', 11.99, 'box', 'Clif Bar', true),
(gen_random_uuid(), 'Protein Bars', 'snacks', 14.99, 'box', 'KIND', true),
(gen_random_uuid(), 'Trail Mix', 'snacks', 6.99, 'bag', 'Kirkland', true),
(gen_random_uuid(), 'Mixed Nuts', 'snacks', 9.99, 'can', 'Planters', true),
(gen_random_uuid(), 'Almonds', 'snacks', 8.99, 'bag', 'Blue Diamond', true),
(gen_random_uuid(), 'Cashews', 'snacks', 10.99, 'bag', 'Planters', true),
(gen_random_uuid(), 'Peanuts', 'snacks', 5.99, 'jar', 'Planters Dry Roasted', true),
(gen_random_uuid(), 'Peanut Butter', 'pantry', 4.99, 'jar', 'Jif Creamy', true),
(gen_random_uuid(), 'Peanut Butter', 'pantry', 4.99, 'jar', 'Skippy Crunchy', true),
(gen_random_uuid(), 'Almond Butter', 'pantry', 9.99, 'jar', 'Justin''s', true),
(gen_random_uuid(), 'Nutella', 'pantry', 5.99, 'jar', 'Hazelnut Spread', true),
(gen_random_uuid(), 'Jam', 'pantry', 4.99, 'jar', 'Smucker''s Strawberry', true),
(gen_random_uuid(), 'Jelly', 'pantry', 3.99, 'jar', 'Welch''s Grape', true),


-- Canned & Jarred Goods - Extensive variety
(gen_random_uuid(), 'Canned Tomatoes', 'pantry', 1.99, 'can', 'Hunt''s', true),
(gen_random_uuid(), 'Canned Tomatoes', 'pantry', 2.49, 'can', 'San Marzano', true),
(gen_random_uuid(), 'Crushed Tomatoes', 'pantry', 1.79, 'can', 'Hunt''s', true),
(gen_random_uuid(), 'Tomato Paste', 'pantry', 1.29, 'can', 'Contadina', true),
(gen_random_uuid(), 'Tomato Sauce', 'pantry', 2.49, 'jar', 'Rao''s', true),
(gen_random_uuid(), 'Tomato Sauce', 'pantry', 1.99, 'jar', 'Prego', true),
(gen_random_uuid(), 'Marinara Sauce', 'pantry', 3.99, 'jar', 'Rao''s', true),
(gen_random_uuid(), 'Alfredo Sauce', 'pantry', 4.99, 'jar', 'Classico', true),
(gen_random_uuid(), 'Pesto', 'pantry', 5.99, 'jar', 'Barilla', true),
(gen_random_uuid(), 'Chicken Broth', 'pantry', 2.99, 'carton', 'Swanson', true),
(gen_random_uuid(), 'Chicken Stock', 'pantry', 3.49, 'carton', 'Pacific Organic', true),
(gen_random_uuid(), 'Beef Broth', 'pantry', 2.99, 'carton', 'Swanson', true),
(gen_random_uuid(), 'Vegetable Broth', 'pantry', 2.99, 'carton', 'Pacific', true),
(gen_random_uuid(), 'Canned Black Beans', 'pantry', 1.49, 'can', 'Bush''s', true),
(gen_random_uuid(), 'Canned Kidney Beans', 'pantry', 1.49, 'can', 'Bush''s', true),
(gen_random_uuid(), 'Canned Chickpeas', 'pantry', 1.49, 'can', 'Goya', true),
(gen_random_uuid(), 'Canned Pinto Beans', 'pantry', 1.29, 'can', 'Bush''s', true),
(gen_random_uuid(), 'Refried Beans', 'pantry', 1.79, 'can', 'Old El Paso', true),
(gen_random_uuid(), 'Canned Corn', 'pantry', 1.29, 'can', 'Green Giant', true),
(gen_random_uuid(), 'Canned Green Beans', 'pantry', 1.29, 'can', 'Del Monte', true),
(gen_random_uuid(), 'Canned Peas', 'pantry', 1.29, 'can', 'Green Giant', true),
(gen_random_uuid(), 'Canned Carrots', 'pantry', 1.29, 'can', 'Del Monte', true),
(gen_random_uuid(), 'Canned Mushrooms', 'pantry', 1.99, 'can', 'Green Giant', true),
(gen_random_uuid(), 'Canned Tuna', 'pantry', 1.49, 'can', 'StarKist', true),
(gen_random_uuid(), 'Canned Tuna', 'pantry', 2.49, 'can', 'Wild Planet', true),
(gen_random_uuid(), 'Canned Salmon', 'pantry', 3.99, 'can', 'Bumble Bee', true),
(gen_random_uuid(), 'Canned Soup', 'pantry', 2.49, 'can', 'Campbell''s Tomato', true),
(gen_random_uuid(), 'Canned Soup', 'pantry', 2.49, 'can', 'Campbell''s Chicken Noodle', true),
(gen_random_uuid(), 'Canned Soup', 'pantry', 3.99, 'can', 'Progresso Minestrone', true),
(gen_random_uuid(), 'Canned Chili', 'pantry', 3.49, 'can', 'Hormel', true),
(gen_random_uuid(), 'Salsa', 'pantry', 3.99, 'jar', 'Pace', true),
(gen_random_uuid(), 'Salsa', 'pantry', 4.99, 'jar', 'Newman''s Own', true),
(gen_random_uuid(), 'Pickles', 'pantry', 3.49, 'jar', 'Claussen', true),
(gen_random_uuid(), 'Pickles', 'pantry', 4.99, 'jar', 'Vlasic', true),
(gen_random_uuid(), 'Olives', 'pantry', 3.99, 'jar', 'Kalamata', true),
(gen_random_uuid(), 'Green Olives', 'pantry', 3.49, 'jar', 'Manzanilla', true),
(gen_random_uuid(), 'Capers', 'pantry', 4.99, 'jar', 'Mezzetta', true),
(gen_random_uuid(), 'Mayo', 'pantry', 5.99, 'jar', 'Hellmann''s', true),
(gen_random_uuid(), 'Mayo', 'pantry', 6.99, 'jar', 'Duke''s', true),
(gen_random_uuid(), 'Mustard', 'pantry', 2.99, 'bottle', 'French''s Yellow', true),
(gen_random_uuid(), 'Dijon Mustard', 'pantry', 3.99, 'jar', 'Grey Poupon', true),
(gen_random_uuid(), 'Whole Grain Mustard', 'pantry', 4.49, 'jar', 'Maille', true),
(gen_random_uuid(), 'Ketchup', 'pantry', 3.49, 'bottle', 'Heinz', true),
(gen_random_uuid(), 'Ketchup', 'pantry', 2.99, 'bottle', 'Hunt''s', true),
(gen_random_uuid(), 'Soy Sauce', 'pantry', 3.99, 'bottle', 'Kikkoman', true),
(gen_random_uuid(), 'Teriyaki Sauce', 'pantry', 4.49, 'bottle', 'Kikkoman', true),
(gen_random_uuid(), 'Worcestershire Sauce', 'pantry', 3.99, 'bottle', 'Lea & Perrins', true),
(gen_random_uuid(), 'Fish Sauce', 'pantry', 4.99, 'bottle', 'Red Boat', true),
(gen_random_uuid(), 'Sriracha', 'pantry', 4.49, 'bottle', 'Huy Fong', true),


-- Beverages - Extensive variety
(gen_random_uuid(), 'Coffee', 'beverages', 9.99, 'bag', 'Starbucks Pike Place', true),
(gen_random_uuid(), 'Coffee', 'beverages', 12.99, 'bag', 'Lavazza', true),
(gen_random_uuid(), 'Coffee', 'beverages', 7.99, 'bag', 'Folgers', true),
(gen_random_uuid(), 'Coffee', 'beverages', 11.99, 'bag', 'Peet''s', true),
(gen_random_uuid(), 'Instant Coffee', 'beverages', 8.99, 'jar', 'Nescafe', true),
(gen_random_uuid(), 'K-Cups', 'beverages', 14.99, 'box', 'Green Mountain', true),
(gen_random_uuid(), 'Tea Bags', 'beverages', 5.99, 'box', 'Lipton Black Tea', true),
(gen_random_uuid(), 'Tea Bags', 'beverages', 6.99, 'box', 'Twinings Earl Grey', true),
(gen_random_uuid(), 'Green Tea', 'beverages', 5.99, 'box', 'Bigelow', true),
(gen_random_uuid(), 'Herbal Tea', 'beverages', 4.99, 'box', 'Celestial Seasonings', true),
(gen_random_uuid(), 'Orange Juice', 'beverages', 4.99, 'carton', 'Simply Orange', true),
(gen_random_uuid(), 'Orange Juice', 'beverages', 3.99, 'carton', 'Tropicana', true),
(gen_random_uuid(), 'Apple Juice', 'beverages', 3.99, 'bottle', 'Martinelli''s', true),
(gen_random_uuid(), 'Cranberry Juice', 'beverages', 4.99, 'bottle', 'Ocean Spray', true),
(gen_random_uuid(), 'Grape Juice', 'beverages', 3.99, 'bottle', 'Welch''s', true),
(gen_random_uuid(), 'Lemonade', 'beverages', 3.99, 'carton', 'Simply', true),
(gen_random_uuid(), 'Lemonade', 'beverages', 2.99, 'carton', 'Minute Maid', true),
(gen_random_uuid(), 'Almond Milk', 'beverages', 3.99, 'carton', 'Silk', true),
(gen_random_uuid(), 'Almond Milk', 'beverages', 4.49, 'carton', 'Califia Farms', true),
(gen_random_uuid(), 'Oat Milk', 'beverages', 4.99, 'carton', 'Oatly', true),
(gen_random_uuid(), 'Oat Milk', 'beverages', 5.49, 'carton', 'Chobani', true),
(gen_random_uuid(), 'Soy Milk', 'beverages', 3.99, 'carton', 'Silk', true),
(gen_random_uuid(), 'Coconut Milk', 'beverages', 4.99, 'carton', 'So Delicious', true),
(gen_random_uuid(), 'Coconut Water', 'beverages', 2.99, 'bottle', 'Vita Coco', true),
(gen_random_uuid(), 'Sparkling Water', 'beverages', 4.99, 'pack', 'LaCroix', true),
(gen_random_uuid(), 'Sparkling Water', 'beverages', 5.99, 'pack', 'Perrier', true),
(gen_random_uuid(), 'Soda', 'beverages', 1.99, 'bottle', 'Coca-Cola', true),
(gen_random_uuid(), 'Soda', 'beverages', 1.99, 'bottle', 'Pepsi', true),
(gen_random_uuid(), 'Soda', 'beverages', 1.99, 'bottle', 'Sprite', true),
(gen_random_uuid(), 'Diet Coke', 'beverages', 1.99, 'bottle', 'Coca-Cola', true),
(gen_random_uuid(), 'Ginger Ale', 'beverages', 1.79, 'bottle', 'Canada Dry', true),
(gen_random_uuid(), 'Sports Drink', 'beverages', 1.99, 'bottle', 'Gatorade', true),
(gen_random_uuid(), 'Sports Drink', 'beverages', 2.49, 'bottle', 'Powerade', true),
(gen_random_uuid(), 'Energy Drink', 'beverages', 2.49, 'can', 'Red Bull', true),
(gen_random_uuid(), 'Energy Drink', 'beverages', 2.99, 'can', 'Monster', true),
(gen_random_uuid(), 'Iced Tea', 'beverages', 1.79, 'bottle', 'Pure Leaf', true),
(gen_random_uuid(), 'Iced Tea', 'beverages', 1.99, 'bottle', 'Arizona', true),
(gen_random_uuid(), 'Iced Coffee', 'beverages', 2.99, 'bottle', 'Starbucks Frappuccino', true),

-- Frozen Foods - Expanded
(gen_random_uuid(), 'Frozen Pizza', 'frozen', 5.99, 'each', 'DiGiorno', true),
(gen_random_uuid(), 'Frozen Pizza', 'frozen', 7.99, 'each', 'California Pizza Kitchen', true),
(gen_random_uuid(), 'Frozen Pizza', 'frozen', 4.99, 'each', 'Tombstone', true),
(gen_random_uuid(), 'Ice Cream', 'frozen', 5.99, 'pint', 'Ben & Jerry''s', true),
(gen_random_uuid(), 'Ice Cream', 'frozen', 6.99, 'pint', 'Haagen-Dazs', true),
(gen_random_uuid(), 'Ice Cream', 'frozen', 3.99, 'container', 'Breyers', true),
(gen_random_uuid(), 'Frozen Yogurt', 'frozen', 4.99, 'container', 'Yasso', true),
(gen_random_uuid(), 'Frozen Chicken Nuggets', 'frozen', 7.99, 'bag', 'Tyson', true),
(gen_random_uuid(), 'Frozen Chicken Tenders', 'frozen', 8.99, 'bag', 'Perdue', true),
(gen_random_uuid(), 'Frozen French Fries', 'frozen', 3.99, 'bag', 'Ore-Ida', true),
(gen_random_uuid(), 'Frozen Tater Tots', 'frozen', 3.49, 'bag', 'Ore-Ida', true),
(gen_random_uuid(), 'Frozen Onion Rings', 'frozen', 4.49, 'bag', 'Alexia', true),
(gen_random_uuid(), 'Frozen Waffles', 'frozen', 3.49, 'box', 'Eggo', true),
(gen_random_uuid(), 'Frozen Pancakes', 'frozen', 3.99, 'box', 'Eggo', true),
(gen_random_uuid(), 'Frozen Burrito', 'frozen', 6.99, 'pack', 'El Monterey', true),
(gen_random_uuid(), 'Frozen Breakfast Sandwich', 'frozen', 7.99, 'pack', 'Jimmy Dean', true),
(gen_random_uuid(), 'Frozen Meatballs', 'frozen', 8.99, 'bag', 'Cooked Perfect', true),
(gen_random_uuid(), 'Frozen Ravioli', 'frozen', 5.99, 'bag', 'Rosina', true),
(gen_random_uuid(), 'Frozen Lasagna', 'frozen', 9.99, 'tray', 'Stouffer''s', true),
(gen_random_uuid(), 'Frozen Mac & Cheese', 'frozen', 4.99, 'tray', 'Stouffer''s', true),
(gen_random_uuid(), 'Frozen Shrimp', 'frozen', 13.99, 'bag', 'Seapak', true),
(gen_random_uuid(), 'Frozen Fish Sticks', 'frozen', 6.99, 'box', 'Gorton''s', true),
(gen_random_uuid(), 'Frozen Vegetables', 'frozen', 2.99, 'bag', 'Mixed Vegetables', true),
(gen_random_uuid(), 'Frozen Broccoli', 'frozen', 2.49, 'bag', 'Green Giant', true),
(gen_random_uuid(), 'Frozen Peas', 'frozen', 2.29, 'bag', 'Birds Eye', true),
(gen_random_uuid(), 'Frozen Corn', 'frozen', 2.29, 'bag', 'Birds Eye', true),
(gen_random_uuid(), 'Frozen Green Beans', 'frozen', 2.49, 'bag', 'Green Giant', true),
(gen_random_uuid(), 'Frozen Berries', 'frozen', 4.99, 'bag', 'Mixed Berries', true),
(gen_random_uuid(), 'Frozen Strawberries', 'frozen', 4.49, 'bag', 'Dole', true),
(gen_random_uuid(), 'Frozen Blueberries', 'frozen', 5.99, 'bag', 'Wyman''s', true),

-- Condiments & Spices - Comprehensive
(gen_random_uuid(), 'Black Pepper', 'spices', 4.99, 'container', 'McCormick', true),
(gen_random_uuid(), 'Salt', 'spices', 2.49, 'container', 'Morton', true),
(gen_random_uuid(), 'Sea Salt', 'spices', 4.99, 'container', 'Maldon', true),
(gen_random_uuid(), 'Garlic Powder', 'spices', 3.99, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Onion Powder', 'spices', 3.99, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Paprika', 'spices', 3.99, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Cayenne Pepper', 'spices', 4.49, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Chili Powder', 'spices', 3.99, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Cumin', 'spices', 4.49, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Oregano', 'spices', 3.49, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Basil', 'spices', 3.49, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Thyme', 'spices', 3.49, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Rosemary', 'spices', 3.99, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Cinnamon', 'spices', 4.99, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Nutmeg', 'spices', 5.49, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Vanilla Extract', 'spices', 8.99, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Almond Extract', 'spices', 6.99, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Italian Seasoning', 'spices', 3.49, 'bottle', 'McCormick', true),
(gen_random_uuid(), 'Everything Bagel Seasoning', 'spices', 4.99, 'bottle', 'Trader Joe''s', true),
(gen_random_uuid(), 'Ranch Dressing', 'condiments', 3.99, 'bottle', 'Hidden Valley', true),
(gen_random_uuid(), 'Caesar Dressing', 'condiments', 4.49, 'bottle', 'Ken''s', true),
(gen_random_uuid(), 'Italian Dressing', 'condiments', 3.49, 'bottle', 'Wish-Bone', true),
(gen_random_uuid(), 'Balsamic Vinaigrette', 'condiments', 4.99, 'bottle', 'Newman''s Own', true),
(gen_random_uuid(), 'Blue Cheese Dressing', 'condiments', 4.99, 'bottle', 'Ken''s', true),
(gen_random_uuid(), 'BBQ Sauce', 'condiments', 3.49, 'bottle', 'Sweet Baby Ray''s', true),
(gen_random_uuid(), 'BBQ Sauce', 'condiments', 4.99, 'bottle', 'Stubb''s', true),
(gen_random_uuid(), 'Hot Sauce', 'condiments', 2.99, 'bottle', 'Tabasco', true),
(gen_random_uuid(), 'Hot Sauce', 'condiments', 4.49, 'bottle', 'Frank''s RedHot', true),
(gen_random_uuid(), 'Buffalo Sauce', 'condiments', 3.99, 'bottle', 'Frank''s', true),

-- Breakfast Cereals & Foods
(gen_random_uuid(), 'Cheerios', 'cereal', 4.99, 'box', 'General Mills', true),
(gen_random_uuid(), 'Honey Nut Cheerios', 'cereal', 4.99, 'box', 'General Mills', true),
(gen_random_uuid(), 'Frosted Flakes', 'cereal', 4.49, 'box', 'Kellogg''s', true),
(gen_random_uuid(), 'Corn Flakes', 'cereal', 3.99, 'box', 'Kellogg''s', true),
(gen_random_uuid(), 'Raisin Bran', 'cereal', 4.49, 'box', 'Kellogg''s', true),
(gen_random_uuid(), 'Fruit Loops', 'cereal', 4.99, 'box', 'Kellogg''s', true),
(gen_random_uuid(), 'Lucky Charms', 'cereal', 4.99, 'box', 'General Mills', true),
(gen_random_uuid(), 'Cinnamon Toast Crunch', 'cereal', 4.99, 'box', 'General Mills', true),
(gen_random_uuid(), 'Special K', 'cereal', 5.49, 'box', 'Kellogg''s', true),
(gen_random_uuid(), 'Granola', 'cereal', 5.99, 'bag', 'Nature Valley', true),
(gen_random_uuid(), 'Granola', 'cereal', 7.99, 'bag', 'Bear Naked', true),
(gen_random_uuid(), 'Pancake Mix', 'pantry', 4.99, 'box', 'Aunt Jemima', true),
(gen_random_uuid(), 'Pancake Mix', 'pantry', 5.99, 'box', 'Kodiak Cakes', true),
(gen_random_uuid(), 'Waffle Mix', 'pantry', 4.99, 'box', 'Bisquick', true),
(gen_random_uuid(), 'Pop-Tarts', 'snacks', 3.99, 'box', 'Strawberry', true),
(gen_random_uuid(), 'Pop-Tarts', 'snacks', 3.99, 'box', 'Brown Sugar Cinnamon', true),

-- Eggs & Breakfast
(gen_random_uuid(), 'Eggs', 'dairy', 3.99, 'dozen', 'Large Grade A', true),
(gen_random_uuid(), 'Eggs', 'dairy', 5.99, 'dozen', 'Organic Free Range', true),
(gen_random_uuid(), 'Egg Whites', 'dairy', 4.99, 'carton', 'Egg Beaters', true),

-- Baking Supplies
(gen_random_uuid(), 'Baking Powder', 'pantry', 2.99, 'can', 'Clabber Girl', true),
(gen_random_uuid(), 'Baking Soda', 'pantry', 1.99, 'box', 'Arm & Hammer', true),
(gen_random_uuid(), 'Yeast', 'pantry', 4.99, 'jar', 'Fleischmann''s', true),
(gen_random_uuid(), 'Corn Starch', 'pantry', 2.99, 'box', 'Argo', true),
(gen_random_uuid(), 'Chocolate Chips', 'pantry', 4.99, 'bag', 'Nestle Toll House', true),
(gen_random_uuid(), 'Cocoa Powder', 'pantry', 6.99, 'container', 'Hershey''s', true),
(gen_random_uuid(), 'Cake Mix', 'pantry', 2.99, 'box', 'Betty Crocker', true),
(gen_random_uuid(), 'Brownie Mix', 'pantry', 2.99, 'box', 'Ghirardelli', true),
(gen_random_uuid(), 'Cookie Mix', 'pantry', 3.49, 'box', 'Betty Crocker', true),
(gen_random_uuid(), 'Frosting', 'pantry', 3.99, 'container', 'Duncan Hines', true),

-- Personal Care (sometimes bought with groceries)
(gen_random_uuid(), 'Shampoo', 'personal', 6.99, 'bottle', 'Pantene', true),
(gen_random_uuid(), 'Shampoo', 'personal', 8.99, 'bottle', 'Herbal Essences', true),
(gen_random_uuid(), 'Conditioner', 'personal', 6.99, 'bottle', 'Pantene', true),
(gen_random_uuid(), 'Conditioner', 'personal', 8.99, 'bottle', 'TRESemmé', true),
(gen_random_uuid(), 'Body Wash', 'personal', 5.99, 'bottle', 'Dove', true),
(gen_random_uuid(), 'Body Wash', 'personal', 6.99, 'bottle', 'Olay', true),
(gen_random_uuid(), 'Bar Soap', 'personal', 4.99, 'pack', 'Dove', true),
(gen_random_uuid(), 'Hand Soap', 'personal', 3.99, 'bottle', 'Method', true),
(gen_random_uuid(), 'Toothpaste', 'personal', 4.99, 'tube', 'Crest', true),
(gen_random_uuid(), 'Toothpaste', 'personal', 5.99, 'tube', 'Colgate', true),
(gen_random_uuid(), 'Toothbrush', 'personal', 3.99, 'pack', 'Oral-B', true),
(gen_random_uuid(), 'Mouthwash', 'personal', 6.99, 'bottle', 'Listerine', true),
(gen_random_uuid(), 'Dental Floss', 'personal', 3.99, 'pack', 'Oral-B Glide', true),
(gen_random_uuid(), 'Deodorant', 'personal', 5.99, 'stick', 'Dove', true),
(gen_random_uuid(), 'Deodorant', 'personal', 6.99, 'stick', 'Old Spice', true),
(gen_random_uuid(), 'Body Lotion', 'personal', 7.99, 'bottle', 'Aveeno', true),
(gen_random_uuid(), 'Hand Lotion', 'personal', 5.99, 'bottle', 'Jergens', true),
(gen_random_uuid(), 'Sunscreen', 'personal', 9.99, 'bottle', 'Coppertone', true),
(gen_random_uuid(), 'Razors', 'personal', 11.99, 'pack', 'Gillette', true),
(gen_random_uuid(), 'Shaving Cream', 'personal', 4.99, 'can', 'Barbasol', true),

-- Household Supplies
(gen_random_uuid(), 'Paper Towels', 'household', 14.99, 'pack', 'Bounty', true),
(gen_random_uuid(), 'Paper Towels', 'household', 12.99, 'pack', 'Brawny', true),
(gen_random_uuid(), 'Toilet Paper', 'household', 19.99, 'pack', 'Charmin', true),
(gen_random_uuid(), 'Toilet Paper', 'household', 16.99, 'pack', 'Scott', true),
(gen_random_uuid(), 'Tissues', 'household', 3.99, 'box', 'Kleenex', true),
(gen_random_uuid(), 'Napkins', 'household', 4.99, 'pack', 'Vanity Fair', true),
(gen_random_uuid(), 'Plastic Wrap', 'household', 4.99, 'box', 'Glad Cling Wrap', true),
(gen_random_uuid(), 'Aluminum Foil', 'household', 5.99, 'box', 'Reynolds Wrap', true),
(gen_random_uuid(), 'Parchment Paper', 'household', 4.99, 'box', 'Reynolds', true),
(gen_random_uuid(), 'Ziploc Bags', 'household', 5.99, 'box', 'Sandwich', true),
(gen_random_uuid(), 'Ziploc Bags', 'household', 6.99, 'box', 'Gallon', true),
(gen_random_uuid(), 'Trash Bags', 'household', 12.99, 'box', 'Glad', true),
(gen_random_uuid(), 'Dish Soap', 'household', 3.99, 'bottle', 'Dawn', true),
(gen_random_uuid(), 'Dishwasher Detergent', 'household', 11.99, 'box', 'Cascade Pods', true),
(gen_random_uuid(), 'Laundry Detergent', 'household', 14.99, 'bottle', 'Tide', true),
(gen_random_uuid(), 'Laundry Detergent', 'household', 12.99, 'bottle', 'Gain', true),
(gen_random_uuid(), 'Fabric Softener', 'household', 7.99, 'bottle', 'Downy', true),
(gen_random_uuid(), 'Dryer Sheets', 'household', 6.99, 'box', 'Bounce', true),
(gen_random_uuid(), 'All-Purpose Cleaner', 'household', 4.99, 'bottle', 'Lysol', true),
(gen_random_uuid(), 'Glass Cleaner', 'household', 4.49, 'bottle', 'Windex', true),
(gen_random_uuid(), 'Disinfecting Wipes', 'household', 5.99, 'canister', 'Clorox', true),
(gen_random_uuid(), 'Bleach', 'household', 4.99, 'bottle', 'Clorox', true),
(gen_random_uuid(), 'Sponges', 'household', 4.99, 'pack', 'Scotch-Brite', true)

ON CONFLICT (item_name) DO NOTHING;

-- ============================================
-- Verification Query
-- ============================================
-- Run this to verify the catalog size:
-- SELECT category, COUNT(*) as item_count FROM amazon_catalog GROUP BY category ORDER BY category;
--
-- Expected result: ~400+ total items across all categories
-- This enriched catalog includes:
-- - Multiple brands for popular items
-- - Various price points (budget, mid-range, premium)
-- - Different sizes and varieties
-- - Organic and conventional options
-- - National brands and store brands
